name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          MAIN_FOLDER=$(pwd)
          SRC_FOLDER=$(pwd)/src

          sudo apt update
          sudo apt install libmicrohttpd-dev

          cd $MAIN_FOLDER
          cd lib/prom/ && mkdir build && cd build
          cmake ..
          make && sudo make install

          cd $MAIN_FOLDER
          cd lib/promhttp/ && mkdir build && cd build
          cmake ..
          make && sudo make install      

          cd $MAIN_FOLDER
          make all
