name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)/src

          sudo mv lib/libprom /usr/local/lib/libprom.so
          sudo mv lib/libpromhttp /usr/local/lib/libpromhttp.so


          make all
