name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)/src

          sudo mv lib/libprom /usr/local/lib/libprom.so
          sudo mv lib/libpromhttp /usr/local/lib/libpromhttp.so
          sudo mv libmicrohttpd /usr/local/lib/libmicrohttpd.so
          
          sudo mv lib/prom /usr/local/include/prom.h
          sudo mv lib/prom_alloc /usr/local/include/prom_alloc.h
          sudo mv lib/prom_collector /usr/local/include/prom_collector.h
          sudo mv lib/prom_collector_registry /usr/local/include/prom_collector_registry.h
          sudo mv lib/prom_counter /usr/local/include/prom_counter.h
          sudo mv lib/prom_gauge /usr/local/include/prom_gauge.h
          sudo mv lib/prom_histogram /usr/local/include/prom_histogram.h
          sudo mv lib/prom_histogram_buckets /usr/local/include/prom_histogram_buckets.h
          sudo mv lib/prom_linked_list /usr/local/include/prom_linked_list.h
          sudo mv lib/prom_map /usr/local/include/prom_map.h
          sudo mv lib/prom_metric /usr/local/include/prom_metric.h
          sudo mv lib/prom_metric_sample /usr/local/include/prom_metric_sample.h
          sudo mv lib/prom_metric_sample_histogram /usr/local/include/prom_metric_sample_histogram.h
          sudo mv lib/promhttp /usr/local/include/promhttp.h
          sudo mv lib/microhttpd /usr/include/microhttpd.h

          make all
